- name: AlAdhan.com
  image: aladhan.jpg
  description: AlAdhan.com is a Prayer Times and Hijri Calendar Web Application and API. It is fully dockerised and the source code is available on GitHub @ <a href="https://github.com/islamic-network" target="_blank">https://github.com/islamic-network</a>. It is used by thousands of people and serves upto 16 million requests a day.
  link: https://aladhan.com
- name: AlQuran.cloud
  image: alquran.jpg
  description: AlQuran.cloud is Quran Web Application, API and CDN making the text and recitations of the blessed Qur'an available in various languages. It is fully dockerised and the source code is available on GitHub @ <a href="https://github.com/islamic-network" target="_blank">https://github.com/islamic-network</a>.
  link: https://alquran.cloud
- name: Islamic Network CDN
  image: mp.jpg
  description: The Islamic CDN provides Quran and other Islamic media for streaming and currently serves upto 20 TB of traffic a month. If there is content you would like to make available via the CDN, please get in touch.
  link: https://alquran.cloud/cdn
- name: Marifa.org
  image: marifa.png
  description: A simple web app that shows metaphysical truths and quotations from saints across Dar al Islam.
  link: https://marifa.org
- name: Perennialism.org
  image: tradition.png
  description: A simple page discussing the traditional definition of the Perennial Philosophy from the Islamic perspective.
  link: https://perennialism.org
- name: Sermons
  image: khutba.jpg
  description: An API for khutbas published by various religious authorities in the Dar al Islam.
  link: https://sermons.islamic.network
- name: AlAqida.com
  image: khutba.jpg
  description: A copy of Imam Tahaawi's Aqida Tahawiyya which represents the creed of the Ahl al Sunna wa al Jama'a.
  link: https://alaqida.com